### ISSUE TITLE
Unable to inflate layout with msdkui components

### ISSUE THREAD

**Issue by Natraj21** [heremaps/msdkui-android#120]
I'm working on demo Guides_Examples ..
Generated MSDKUILib-release.arr and placed in lib folder
when trying to execute the code of activity which contains msdkui components.. (com.here.msdkui.routing.WaypointList and com.here.msdkui.routing.TransportModePanel) I've faced inflate exception...

Could you please suggest what I'm missing

 Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: You must supply a layout_width attribute.

  Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.here.msdkui.guidance.GuidanceManeuverView
     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.here.msdkui.guidance.GuidanceManeuverView
     Caused by: java.lang.reflect.InvocationTargetException

**Comment by datasun** [comment]
Hi Natraj21, can you try to revert all local changes from your code base and build again from a clean state? To narrow down the problem it might also help to know which app you are trying to build - as well as some more details like, for example, which version of Android Studio you are using. Thanks.

**Comment by Natraj21** [comment]
Hey Lucka, thanks...
Please find Attachment

this is my xml

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical" >

    <com.here.msdkui.guidance.GuidanceManeuverView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

    <fragment
        class="com.here.android.mpa.mapping.SupportMapFragment"
        android:id="@+id/mapFragment"
        android:layout_width="fill_parent"
        android:layout_height="0dp"
        android:layout_weight="1"/>

    <Button
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:text="Stop guidance"
        android:onClick="onStopGuidanceButtonClick"/>

</LinearLayout>

**Comment by datasun** [comment]
Thanks for pasting your layout snippet. It seems you are trying to build an example app? I would recommend to checkout the original source code of the example and try again. Your code snippet above contains some modifications. However, your error log seems to point to the GuidanceManeuverView's layout, rather than to the layout file above. Without seeing your full code it's hard to say what goes wrong, so I would suggest to try one of the example apps instead - without any modifications. Please make sure to reset your repo to a clean state before trying and follow the instructions in the Quick Start guide. This way you can ensure that at least your tool chain is set up properly.

**Comment by Natraj21** [comment]
Hey thanks for following up,

Just am trying with blank activity and the layout contains only msdkui
components. Apart from that nothing I've implemented.  Please could you
send the original source code example link.

**Comment by datasun** [comment]
Sure, no problem. The full example can be found here: https://github.com/heremaps/msdkui-android/tree/master/Documentation/Guides_Examples/MSDKUIPrimer

Be sure to build the MSDKUI lib first. You'll also need the HERE Mobile SDK 3.10.1. Both AAR files must be added to the example app's libs folder.

**Comment by Natraj21** [comment]
Yeah, I've implented from this example only .. but its throwing same error.
To cross check the msdkuilib-release.arr I've executed unit-test cases but
the results are still pending. Please find attachment of test case logs.

**Comment by datasun** [comment]
I cannot find the attached logs. But maybe it's worth to try the HelloMSDKUI example app instead. It does not contain the GuidanceManeuverView. So, you should be able to build HelloMESDKUI. From there it would be easier to narrow down your problems. Also, it would be great if you can share info about what concrete steps you are doing - and some info about your setup and Android Studio version. And please check the minimum requirements for this project to see if all are met. Hope this helps.

**Comment by ShreyashSingh007** [comment]
@datasun @Natraj21 the solution to this problem is actually modifying you app theme. Please make sure that the base theme of you activity actually uses "MSDKUIDarkTheme" in both of the style.xml (normal & /v21).

Cheers!

**Comment by datasun** [comment]
Without seeing the logs, it is hard to say what is your problem. But yes, using MSDKUIDarkTheme is a required step. It's also mentioned [here](https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/QuickStart.md). In addition, you can check the example apps to see how it is done there. If this was not your issue, please reopen this ticket. Thanks.
