### ISSUE TITLE
packacke com.here.android.mpa.guidance does not exist

### ISSUE THREAD

**Issue by Reiszecke** [heremaps/msdkui-android#140]
Downloaded the project, opened MSDKUIKit, added HERE-sdk.aar, invalidated caches + restart, trying to build, got this issue.

![image](https://user-images.githubusercontent.com/11237541/63814196-6153b600-c930-11e9-8539-2afc606487bd.png)

Anything I missed?

**Comment by datasun** [comment]
Did you followed the steps from this [guide](https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/ContributionGuide.md#building-the-here-ui-kit-library)? Make sure to execute the gradle task `:MSDKUILib:assemble`, if not done already. If you can provide more info on the steps and versions you are using, it will be easier to provide help.

**Comment by stefan-troyke** [comment]
Hi,

where did you add the HERE-sdk.aar exactly?
