### ISSUE TITLE
Incompatable with Here SDK 3.13

### ISSUE THREAD

**Issue by william-reed** [heremaps/msdkui-android#144]
Trying to get the demo project and it seems that the ui kit is incompatable with the most recent SDK release due to the removal of `Route.getTta`. Might be other issues too but this was the first thing that blocked me.

**Comment by datasun** [comment]
You are right, 3.13 was released just three days ago. Currently, we only support HERE Mobile SDK 3.12. Stay tuned, a new MSDKUI release to support HERE Mobile SDK 3.13 is hopefully coming soon!

**Comment by chrisfischer** [comment]
This issue has not yet been resolved, can you please reopen it until the UI Kit is updated?

**Comment by stefan-troyke** [comment]
The UI Kit supports HERE SDK 3.13 now. Please check the release https://github.com/heremaps/msdkui-android/releases/tag/2.1.3
