### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

### ISSUE THREAD

**Issue by Irpan98** [heremaps/msdkui-android#145]
Hi,
just getting problem when trying using MSDKUIKit
just getting error like this
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.

just using HERE_Android_SDK_Premium_v3.13.2_86.
 please help

**Comment by stefan-troyke** [comment]
Hi,

we will look into this.

**Comment by stefan-troyke** [comment]
Hi,

Gradle 6.0 is not officially released yet and just RC1 is available. We will update the tool chain once Gradle 6 is available as current version. We keep this ticket open unless this is the case.

**Comment by stefan-troyke** [comment]
Fixed in the latest release
