### ISSUE TITLE
Usage of deprecated constraint layout features

### ISSUE THREAD

**Issue by william-reed** [heremaps/msdkui-android#147]
Tons of these errors: `E/ConstraintLayout: layout_constraintWidth_default="wrap" is deprecated.`

Might get around to fixing these if possible

**Comment by stefan-troyke** [comment]
Hi,

we will look into this.

**Comment by tstaszak89** [comment]
Fixed in this commit: https://github.com/heremaps/msdkui-android/commit/8332c2315bc7be1628783b5a71df625f6d28eb6f
