### ISSUE TITLE
AAPT: error: style attribute 'attr/tabMode' not found.

### ISSUE THREAD

**Issue by william-reed** [heremaps/msdkui-android#152]
Last week I created #146 to fix what I thought was a bug. After the comments @tstaszak89 it appears something else might be going on. I have just reproduced the error by creating a new android project through android studio with a blank main activity, and then I have added MSDKUI v2.1.2 as well as HERE 3.1.2. When trying to build the application I get the following two errors

```
AAPT: error: style attribute 'attr/tabGravity (aka dev.williamreed.myapplication:attr/tabGravity)' not found.
    
AAPT: error: style attribute 'attr/tabMode (aka dev.williamreed.myapplication:attr/tabMode)' not found.
```

Here is the repository demonstrating the issue
https://github.com/william-reed/here-ui-kit-style-attr-issue

**Comment by tstaszak89** [comment]
The investigation of this issue is in progress.

**Comment by tstaszak89** [comment]
After taking a close look at your repository I figured out that you are missing `implementation 'com.google.android.material:material:1.0.0'` in your app build.gradle file. Here you can find information what dependencies are required to use MSDKUIKit: https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/QuickStart.md#gradle-setup
