### ISSUE TITLE
Incompatible with Here SDK 3.14

### ISSUE THREAD

**Issue by EdwarDDay** [heremaps/msdkui-android#156]
In the Here SDK 3.14 `NavigationManager.ReroutListener.onRerouteEnd(RouteResult)` and `NavigationManager.RerouteListener.onRerouteFailed` were deleted. Because of this I can't build the current release version of this Library (`com.here.msdkui.guidance.base.BaseGuidancePresenter` line 96 and line 100 are erroneous)

**Comment by datasun** [comment]
HERE Premium SDK 3.14 is not yet supported. The MSDKUI framework supports only version 3.13. We hope to add support for a newer version soon.
