### ISSUE TITLE
Unable start GuidanceManeuverPresenter

### ISSUE THREAD

**Issue by Natraj21** [heremaps/msdkui-android#166]
Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
  Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
  Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
  Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
  Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)

  Accessing hidden method Landroid/view/View;- 
  >computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, 
  reflection)
 Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light 
  greylist, reflection)
 Accessing hidden method Landroid/widget/TextView;- 
 >getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)

**Comment by jehovahmidara** [comment]
@Natraj21 , Can you provide detailed description as to what your issue is.
