### ISSUE TITLE
Waypoint List

### ISSUE THREAD

**Issue by edurocks** [heremaps/msdkui-android#168]
Hi guys. I have a problem with this widget com.here.msdkui.routing.WaypointList when I include this in my xml I received an error saying     Caused by: java.lang.UnsupportedOperationException: Binary XML file line #18: You must supply a layout_width attribute but I am specifiying a layout width. How can i resolve this problem? Thanks.

**Comment by datasun** [comment]
Hi edurocks, check if all nested layouts contain the layout_width attribute. If that does not help, please paste the affected part of your layout and we'll be happy to take a loot. Thanks.

**Comment by edurocks** [comment]
> Hi edurocks, check if all nested layouts contain the layout_width attribute. If that does not help, please paste the affected part of your layout and we'll be happy to take a look. Thanks.

Yes it is all right. I will paste here my layout. 

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:animateLayoutChanges="true"
    android:id="@+id/maps"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".fragment.MapsFragment">

    <fragment
        android:id="@+id/maps_fragment"
        class="com.here.android.mpa.mapping.AndroidXMapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <androidx.appcompat.widget.AppCompatButton
        android:id="@+id/recenter_map"
        android:layout_width="wrap_content"
        android:layout_height="36dp"
        android:textAllCaps="true"
        android:textSize="14sp"
        android:visibility="gone"
        app:fontFamily="@font/inter_bold"
        android:layout_marginTop="10dp"
        android:layout_marginStart="12dp"
        android:paddingStart="12dp"
        android:paddingEnd="12dp"
        android:paddingTop="9dp"
        android:paddingBottom="9dp"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="20dp"
        android:textColor="@android:color/white"
        android:background="@drawable/ripple_effect"
        android:text="@string/recenter_map"/>


    <com.here.msdkui.routing.WaypointList
        android:id="@+id/waypointList"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

    <RelativeLayout
        android:id="@+id/search_container"
        android:layout_width="329dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="50dp"
        android:layout_marginStart="12dp"
        android:background="@drawable/location_background"
        tools:ignore="RelativeOverlap">

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/location_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/destination_title"
            android:textSize="14sp"
            android:textAllCaps="true"
            android:textStyle="bold"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="12dp"
            android:layout_marginStart="12dp"
            android:layout_marginEnd="39dp"
            android:textColor="@color/colorTextEta"/>

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/marker"
            android:layout_width="32dp"
            android:layout_height="32dp"
            android:layout_marginTop="12dp"
            android:layout_marginStart="12dp"
            android:layout_below="@+id/location_title"
            android:src="@drawable/ic_marker"/>

        <androidx.appcompat.widget.AppCompatAutoCompleteTextView
            android:id="@+id/destination_value"
            android:layout_width="275dp"
            android:layout_height="wrap_content"
            android:layout_below="@+id/location_title"
            android:layout_toEndOf="@+id/marker"
            android:textColor="@color/colorTextAutoComplete"
            app:fontFamily="@font/inter_medium"
            android:textSize="18sp"
            android:dropDownHeight="400dp"
            android:completionThreshold="3"
            android:layout_marginTop="3dp"
            android:layout_marginBottom="12dp"
            android:layout_marginEnd="12dp"
            android:dropDownAnchor="@id/destination_value"
            android:dropDownWidth="265dp"
            android:dropDownHorizontalOffset="6dp"
            app:backgroundTint="@color/colorLineAutoComplete"
            android:dropDownVerticalOffset="3dp"
            android:inputType="textCapWords"
            android:hint="@string/destination_hint" />

    </RelativeLayout>

    <androidx.cardview.widget.CardView
        android:id="@+id/voice_on"
        android:visibility="visible"
        app:cardElevation="4dp"
        android:layout_marginTop="60dp"
        android:layout_marginEnd="12dp"
        android:layout_alignParentEnd="true"
        app:cardCornerRadius="4dp"
        app:cardBackgroundColor="@android:color/transparent"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <androidx.appcompat.widget.AppCompatImageButton
            android:id="@+id/voice_alert_on"
            android:layout_width="42dp"
            android:layout_height="42dp"
            android:background="@drawable/ic_sound_on"/>

    </androidx.cardview.widget.CardView>

    <androidx.cardview.widget.CardView
        android:id="@+id/voice_off"
        android:visibility="gone"
        app:cardElevation="4dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:cardCornerRadius="4dp"
        android:layout_marginTop="60dp"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="12dp">

        <androidx.appcompat.widget.AppCompatImageButton
            android:id="@+id/voice_alert_off"
            android:layout_width="42dp"
            android:layout_height="42dp"
            android:background="@drawable/ic_off_active"/>

    </androidx.cardview.widget.CardView>

    <androidx.cardview.widget.CardView
        android:id="@+id/location"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="108dp"
        app:cardElevation="4dp"
        app:cardCornerRadius="4dp"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="12dp">

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/obstacles"
        android:layout_width="42dp"
        android:layout_height="42dp"
        android:background="@drawable/ic_location"/>

    </androidx.cardview.widget.CardView>

    <androidx.cardview.widget.CardView
        android:id="@+id/parking"
        android:layout_alignParentEnd="true"
        android:layout_below="@+id/location"
        android:layout_marginTop="6dp"
        android:layout_marginEnd="12dp"
        app:cardElevation="4dp"
        app:cardCornerRadius="4dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/parking_off"
        android:layout_width="42dp"
        android:layout_height="42dp"
        android:background="@drawable/ic_parking"/>

     <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/parking_active"
        android:layout_width="42dp"
        android:layout_height="42dp"
        android:background="@drawable/ic_parking_active"/>

    </androidx.cardview.widget.CardView>

    <androidx.cardview.widget.CardView
        android:id="@+id/fuel_station"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:cardElevation="4dp"
        app:cardCornerRadius="4dp"
        android:layout_below="@+id/parking"
        android:layout_marginTop="6dp"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="12dp">

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/fuel_station_off"
        android:layout_width="42dp"
        android:layout_height="42dp"
        android:background="@drawable/ic_fuel_station"/>

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/fuel_station_active"
        android:layout_width="42dp"
        android:layout_height="42dp"
        android:background="@drawable/ic_fuel_station_active"/>

    </androidx.cardview.widget.CardView>

    <androidx.cardview.widget.CardView
        android:id="@+id/map"
        app:cardElevation="4dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="420dp"
        app:cardCornerRadius="4dp"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="12dp">

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/map_icon"
        android:layout_width="42dp"
        android:layout_height="42dp"
        android:background="@drawable/ic_map"/>

        <androidx.appcompat.widget.AppCompatImageButton
            android:id="@+id/map_close_icon"
            android:layout_width="42dp"
            android:layout_height="42dp"
            android:background="@drawable/ic_close_map"
            android:visibility="invisible" />

    </androidx.cardview.widget.CardView>

    <androidx.cardview.widget.CardView
        android:id="@+id/my_location_card_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:cardElevation="4dp"
        app:cardCornerRadius="4dp"
        android:layout_below="@+id/map"
        android:layout_marginTop="6dp"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="12dp">

    <androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/my_location"
        android:layout_width="42dp"
        android:layout_height="42dp"
        android:src="@drawable/ic_gps_location" />

    </androidx.cardview.widget.CardView>

    <androidx.cardview.widget.CardView
        android:layout_below="@+id/my_location_card_view"
        android:layout_width="42dp"
        android:layout_height="75dp"
        app:cardElevation="4dp"
        app:cardCornerRadius="4dp"
        android:layout_alignParentEnd="true"
        android:layout_marginEnd="12dp"
        android:layout_marginTop="6dp">

    <androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/zoom_in"
        android:layout_width="27dp"
        android:layout_height="27dp"
        android:layout_gravity="center_horizontal"
        android:src="@drawable/ic_zoom_in"
        android:layout_marginTop="5dp"
        android:layout_below="@+id/my_location_card_view" />

    <View
        android:layout_width="24dp"
        android:layout_height="1dp"
        android:layout_marginTop="39dp"
        android:layout_gravity="center_horizontal"
        android:background="@color/colorDivider" />

    <androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/zoom_out"
        android:layout_width="27dp"
        android:layout_height="27dp"
        android:src="@drawable/ic_zoom_out"
        android:layout_marginTop="43dp"
        android:layout_gravity="center_horizontal"
        android:layout_below="@+id/my_location_card_view" />

    </androidx.cardview.widget.CardView>

    <include layout="@layout/layout_obstacles" android:id="@+id/map_obstacles"/>

    <include layout="@layout/layout_map_mode" android:id="@+id/map_styles_mode"/>

    <include
        android:id="@+id/travel_information_end"
        layout="@layout/layout_travel_end" />

    <RelativeLayout
        android:id="@+id/travel_information"
        android:layout_width="331dp"
        android:layout_height="165dp"
        android:layout_marginStart="11dp"
        android:layout_marginTop="142dp"
        android:visibility="gone"
        android:background="@drawable/eta_background">

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/road_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="18sp"
            android:maxWidth="310dp"
            app:fontFamily="@font/inter_medium"
            android:layout_marginTop="24dp"
            android:layout_marginStart="12dp"
            android:textColor="@color/colorTextTitle" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/total_time"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            app:fontFamily="@font/inter_medium"
            android:layout_marginTop="24dp"
            android:layout_alignParentEnd="true"
            android:layout_marginEnd="12dp"
            android:textColor="@color/colorTextTitle"
            tools:ignore="RelativeOverlap" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/total_distance"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="18sp"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="8dp"
            android:layout_alignParentEnd="true"
            android:layout_marginEnd="12dp"
            android:layout_below="@+id/total_time"
            android:textColor="@color/colorTextTitle"/>

        <View
            android:id="@+id/separator"
            android:layout_width="407dp"
            android:layout_height="1dp"
            android:background="@color/colorStatusBar"
            android:layout_marginTop="28dp"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_below="@+id/total_distance"/>

        <androidx.appcompat.widget.AppCompatButton
            android:id="@+id/show_eta"
            android:layout_width="wrap_content"
            android:layout_height="36dp"
            android:text="@string/show_eta"
            android:textAllCaps="true"
            android:textSize="14sp"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="10dp"
            android:layout_marginStart="12dp"
            android:paddingStart="12dp"
            android:paddingEnd="12dp"
            android:paddingTop="9dp"
            android:paddingBottom="9dp"
            android:layout_below="@+id/separator"
            android:textColor="@android:color/white"
            android:background="@drawable/ripple_effect"/>

    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/eta_container"
        android:layout_width="329dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="12dp"
        android:visibility="gone"
        android:layout_marginTop="140dp"
        android:background="@drawable/eta_background">

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/eta_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/eta"
            android:textAllCaps="true"
            android:textSize="14sp"
            android:textColor="@color/colorTextEta"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="18dp"
            android:layout_marginStart="12dp"/>

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/eta_value"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/eta_title"
            android:textSize="18sp"
            android:textColor="@color/colorTextTitle"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="4dp"
            android:layout_marginStart="12dp"/>

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/togo_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/to_go"
            android:textAllCaps="true"
            android:textSize="14sp"
            android:layout_toEndOf="@+id/eta_title"
            android:textColor="@color/colorTextEta"
            android:layout_marginStart="93dp"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="18dp" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/togo_value_distance"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/togo_title"
            android:layout_toEndOf="@+id/eta_value"
            android:textSize="18sp"
            android:textColor="@color/colorTextTitle"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="4dp"
            android:layout_marginStart="69dp"/>

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/eta_separator"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@+id/togo_title"
            android:layout_toEndOf="@+id/togo_value_distance"
            android:textSize="18sp"
            android:text="@string/dot"
            android:textColor="@color/colorTextTitle"
            app:fontFamily="@font/inter_bold"
            android:layout_marginStart="10dp"/>

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/togo_value_total_time"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:textSize="18sp"
            android:layout_below="@+id/togo_title"
            android:layout_toEndOf="@+id/eta_separator"
            android:textColor="@color/colorTextTitle"
            app:fontFamily="@font/inter_bold"
            android:layout_marginTop="4dp"
            android:layout_marginStart="10dp"/>

    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/positive_dialog"
        android:layout_width="435dp"
        android:layout_height="78dp"
        android:layout_marginTop="470dp"
        android:layout_centerHorizontal="true"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="12dp"
        android:visibility="gone"
        android:background="@drawable/background_positive_dialog">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/image_counter_positive"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="39dp"
            android:layout_marginTop="12dp"
            android:elevation="1dp"
            android:src="@drawable/counter_positive"/>

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/counter_positive"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:elevation="1dp"
            android:textSize="13sp"
            android:gravity="center"
            app:fontFamily="@font/inter_medium"
            android:layout_alignStart="@id/image_counter_positive"
            android:layout_alignTop="@id/image_counter_positive"
            android:layout_alignEnd="@id/image_counter_positive"
            android:layout_alignBottom="@id/image_counter_positive"
            android:textColor="@android:color/white" />

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/icon_positive"
            android:layout_width="42dp"
            android:layout_height="42dp"
            android:layout_centerVertical="true"
            android:src="@drawable/acceleration_positive_dialog"
            android:layout_marginStart="12dp" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/title_positive"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/positive_message"
            android:textSize="18sp"
            app:fontFamily="@font/inter_medium"
            android:layout_marginTop="15dp"
            android:layout_marginStart="27dp"
            android:textColor="@color/colorTextTitle"
            android:layout_toEndOf="@+id/icon_positive" />

    </RelativeLayout>

    <ProgressBar
        android:id="@+id/progress_bar_positive"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_marginTop="525dp"
        android:layout_marginStart="670dp"
        style="?android:attr/progressBarStyleHorizontal"
        android:background="@drawable/progress_bar"
        android:max="100"
        android:progress="65"
        android:visibility="gone"
        android:progressDrawable="@drawable/circular_progress_bar"/>

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/btn_close"
        android:layout_width="38dp"
        android:layout_height="38dp"
        android:visibility="gone"
        tools:targetApi="m"
        android:src="@drawable/ic_close"
        android:background="@drawable/circle"
        android:layout_marginTop="530dp"
        android:layout_marginStart="675dp" />

    <RelativeLayout
        android:id="@+id/negative_dialog"
        android:layout_width="435dp"
        android:layout_height="78dp"
        android:layout_marginTop="470dp"
        android:layout_centerHorizontal="true"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="12dp"
        android:visibility="gone"
        android:background="@drawable/background_negative_dialog">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/image_counter"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="39dp"
            android:layout_marginTop="12dp"
            android:elevation="1dp"
            android:src="@drawable/counter_negative"/>

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/counter_negative"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:elevation="1dp"
            android:textSize="13sp"
            android:gravity="center"
            app:fontFamily="@font/inter_medium"
            android:layout_alignTop="@id/image_counter"
            android:layout_alignStart="@id/image_counter"
            android:layout_alignEnd="@id/image_counter"
            android:layout_alignBottom="@id/image_counter"
            android:textColor="@android:color/white" />

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/icon_negative"
            android:layout_width="42dp"
            android:layout_height="42dp"
            android:layout_centerVertical="true"
            android:src="@drawable/acceleration_negative_dialog"
            android:layout_marginStart="12dp" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/title_negative"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/negative_message"
            android:textSize="18sp"
            app:fontFamily="@font/inter_medium"
            android:layout_centerVertical="true"
            android:layout_toEndOf="@+id/icon_negative"
            android:layout_marginStart="27dp"
            android:textColor="@color/colorTextTitle"/>

    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/neutral_dialog"
        android:layout_width="435dp"
        android:layout_height="78dp"
        android:layout_marginTop="470dp"
        android:layout_centerHorizontal="true"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="12dp"
        android:visibility="gone"
        android:background="@drawable/background_neutral_dialog">

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/icon_neutral"
            android:layout_width="42dp"
            android:layout_height="42dp"
            android:layout_centerVertical="true"
            android:layout_marginStart="12dp" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/title_neutral"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/negative_message"
            android:textSize="18sp"
            app:fontFamily="@font/inter_medium"
            android:layout_toEndOf="@+id/icon_neutral"
            android:layout_marginTop="15dp"
            android:layout_marginStart="18dp"
            android:textColor="@color/colorTextTitle"/>

    </RelativeLayout>

    <ProgressBar
        android:id="@+id/progress_bar_negative"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_marginTop="525dp"
        android:layout_marginStart="670dp"
        style="?android:attr/progressBarStyleHorizontal"
        android:background="@drawable/progress_bar"
        android:max="100"
        android:progress="100"
        android:visibility="gone"
        android:progressDrawable="@drawable/circular_progress_bar_negative"/>

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/btn_close_negative"
        android:layout_width="38dp"
        android:layout_height="38dp"
        android:src="@drawable/ic_close"
        android:background="@drawable/circle"
        android:layout_marginTop="530dp"
        android:layout_marginStart="675dp"
        android:visibility="gone"
        tools:targetApi="m" />

    <ProgressBar
        android:id="@+id/progress_bar_neutral"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_marginTop="525dp"
        android:layout_marginStart="670dp"
        style="?android:attr/progressBarStyleHorizontal"
        android:background="@drawable/progress_bar"
        android:max="100"
        android:progress="65"
        android:visibility="gone"
        android:progressDrawable="@drawable/circular_progress_bar_neutral"/>

    <androidx.appcompat.widget.AppCompatImageButton
        android:id="@+id/btn_close_neutral"
        android:layout_width="38dp"
        android:layout_height="38dp"
        android:src="@drawable/ic_close"
        android:background="@drawable/circle"
        android:layout_marginTop="530dp"
        android:layout_marginStart="675dp"
        android:visibility="gone"
        tools:targetApi="m" />

</RelativeLayout>`

**Comment by datasun** [comment]
It's a fragment. Could be related to the root layout you are using. But first, please check if you have set up the [theme](https://github.com/heremaps/msdkui-android/blob/master/Documentation/Guides/QuickStart.md#theme-setup) correctly.
