### ISSUE TITLE
Truck options panel update

### ISSUE THREAD

**Issue by Azbesciak** [heremaps/msdkui-android#195]
Hello,
current truck options look a little bit strange in terms of modern design patterns - label on the side, some modal on edit (this is pros or cons because I had an unsolved problem with `EditText` and `BottomSheetFragment` for example).
Maybe it is worth considering to migrate to Material inputs ([`TextInputLayout` and `TextInputEditText`](https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout)), add suffixes for these inputs to let the user know which unit is used (tonne/kilograms), maybe some icon on the left to be more intuitive [not mentioning that some users may use different not available language]?
Thanks

**Comment by datasun** [comment]
Hello @Azbesciak, thanks a lot for the suggestions. Switching to Material indeed may be an option worth to consider. Also, the other points make sense and we will look into it. However, we cannot promise yet if and when this can be integrated / changed.
