### ISSUE TITLE
WeGo map context menu

### ISSUE THREAD

**Issue by Azbesciak** [heremaps/msdkui-android#197]
Hello, is it possible to share the code of the wego context menu in this lib? Or the best component which allows putting your own custom menu items.
I am talking about this on the image.
![image](https://user-images.githubusercontent.com/17334466/112816609-e01b5280-9081-11eb-8eb6-c5e103ff3562.png)

Thanks

**Comment by datasun** [comment]
Hi @Azbesciak, I am afraid this is not planned near term. The WeGo app is using a custom algorithm that is beyond the scope of the MSDKUI demo application.
