### ISSUE TITLE
MSDKUI for the Navigate Edition of Here Maps

### ISSUE THREAD

**Issue by agap** [heremaps/msdkui-android#211]
Hey,

I know this is probably not the right place to ask since this SDK is in the maintenance mode, so I totally understand if you close it without answer, but I'd like to know - should we expect something similar to this SDK for Here's Navigate edition? `GuidanceManeuverView` and `GuidanceSpeedView` saved me a lot of headache in past, and it would be great something of that kind when we migrate to Navigate Edition (which has to be done until the end of 2022).

**Comment by stefan-troyke** [comment]
Hi,

unfortunately a UI Kit for the HERE SDK 4.x is not planned yet. Nevertheless based on the latest technology we provide the HERE SDK reference application for Flutter. See also https://github.com/heremaps/here-sdk-ref-app-flutter. You can reuse the desired screen based on your needs. Note, there is no additional support for iOS or Android specific components at this moment.
